sudo: required
services:
  - docker

before_script:
  - echo -e $sandbox_pavel > ~/.ssh/sandbox_pavel
  - chmod 600 ~/.ssh/*
  - chmod 644 ~/.ssh/config
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/sandbox_pavel

script:
  - ls -al ~/.ssh
  