sudo: required
services:
  - docker
branches:
  only:
    - master
    - /rc-.*/


before_script:
  - echo -e "Host *\\n\tStrictHostKeyChecking no\\n" > ~/.ssh/config
  - echo -e $sandbox > ~/.ssh/sandbox
  - chmod 600 ~/.ssh/*
  - chmod 644 ~/.ssh/config
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/sandbox

script:
  - ls -al ~/.ssh
  - echo test
  